# Generated by Django 5.2 on 2025-04-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncysession',
            name='session_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
