# Generated by Django 5.2 on 2025-04-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_api', '0002_ncysession_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncysession',
            name='key',
            field=models.BinaryField(),
        ),
    ]
